import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

// Initialize Gemini
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for JSON parsing
  app.use(express.json());

  // AI Video Engine: Analysis & Scripting
  app.post("/api/video/script", async (req, res) => {
    const { content, type } = req.body;
    
    try {
      const prompt = `
        You are a Cinematic AI Video Director specializing in Educational Content for competitive exams (RPSC).
        The user has provided this content: "${content}"
        The video type requested is: "${type || 'Reel'}"
        
        Create a detailed storyboard for a 15-30 second educational video.
        Follow these "Suzume" and "Anime Cinematic" visual rules:
        - High-quality anime visuals, environment lighting like Shinkai films.
        - Protagonist: A study assistant character (Anime topper style) or a cute wild cat cub mascot.
        - Scenes should have natural forest lighting, realistic shadows, and particles.
        
        Generate exactly 4 scenes. For each scene, provide:
        1. Visual Prompt (detailed for an image generator)
        2. Narration Script (Short, impactful)
        3. On-screen text (Keywords)
        4. Camera movement (e.g., slow zoom, pan right)
        5. Music vibe
        6. Duration in seconds (sum should be around 20-30s)
      `;

      const result = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              summary: { type: Type.STRING },
              scenes: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    visualPrompt: { type: Type.STRING },
                    narration: { type: Type.STRING },
                    overlayText: { type: Type.STRING },
                    camera: { type: Type.STRING },
                    duration: { type: Type.NUMBER },
                    music: { type: Type.STRING }
                  },
                  required: ["visualPrompt", "narration", "overlayText", "camera", "duration", "music"]
                }
              },
              characterState: { type: Type.STRING, description: "mascot emotion for the video" }
            },
            required: ["title", "summary", "scenes", "characterState"]
          }
        }
      });

      res.json(JSON.parse(result.text || "{}"));
    } catch (error) {
      console.error("Video Script Error:", error);
      res.status(500).json({ error: "Failed to generate video script" });
    }
  });

  // AI Video Engine: Visual Generation
  app.post("/api/video/visual", async (req, res) => {
    const { prompt } = req.body;
    
    try {
      // Use gemini-2.5-flash-image for general AI imagery
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: `${prompt}, high quality anime cinematic style, suzume environment lighting, 4k, digital art, vibrant colors, realistic shadows` }],
        },
        config: {
          imageConfig: {
            aspectRatio: "9:16", // Default to vertical/reel format
            imageSize: "1K"
          }
        }
      });

      let imageUrl = "";
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (imageUrl) {
        res.json({ imageUrl });
      } else {
        throw new Error("No image generated by model");
      }
    } catch (error) {
      console.error("Visual Gen Error:", error);
      res.status(500).json({ error: "Failed to generate visual" });
    }
  });

  // ULTRA-FAST QUIZ GENERATION
  app.post("/api/quiz/generate", async (req, res) => {
    const { subject, difficulty, language, topic, count = 10, mode } = req.body;
    
    try {
      const isDaily = mode === 'daily';
      const prompt = `
        TASK: Generate an PRECISE high-quality MCQ quiz for exclusively the subject: "${subject}".
        STYLE: ${isDaily ? 'Daily Mixed Practice' : 'Subject-focused exam level'}
        TOPIC: ${topic && topic !== 'General' ? topic : `Core ${subject} syllabus (No mix-ins)`}
        DIFFICULTY: ${difficulty}
        LANGUAGE: ${language} (Hinglish means Hindi text written in Roman script mixed with English).
        COUNT: ${count}

        STRICT EXAM RULES:
        1. CONTENT PURITY: Only generate questions for ${subject}. If subject is Reasoning, only reasoning. If GK, only GK. DO NOT mix.
        2. NO unnecessary text. NO markdown code blocks like \`\`\`json.
        3. Real exam-level quality: RPSC, REET, SSC, UPSC, CET, Railway, Police style.
        4. Options must be clear and distractors must be plausible.
        5. Return STRICT JSON object only.
        6. Support ${language} fluently. If Hinglish, use Roman script for Hindi words.

        JSON FORMAT:
        {
          "quiz_title": "${subject} ${isDaily ? 'Daily Challenge' : 'Practice'}",
          "language": "${language}",
          "difficulty": "${difficulty}",
          "questions": [
            {
              "question_no": 1,
              "question": "string",
              "options": {
                "A": "string",
                "B": "string",
                "C": "string",
                "D": "string"
              },
              "correct_answer": "A",
              "explanation": "short impactful explanation"
            }
          ]
        }
      `;

      const result = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              quiz_title: { type: Type.STRING },
              language: { type: Type.STRING },
              difficulty: { type: Type.STRING },
              questions: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    question_no: { type: Type.NUMBER },
                    question: { type: Type.STRING },
                    options: {
                      type: Type.OBJECT,
                      properties: {
                        A: { type: Type.STRING },
                        B: { type: Type.STRING },
                        C: { type: Type.STRING },
                        D: { type: Type.STRING }
                      },
                      required: ["A", "B", "C", "D"]
                    },
                    correct_answer: { type: Type.STRING, enum: ["A", "B", "C", "D"] },
                    explanation: { type: Type.STRING }
                  },
                  required: ["question_no", "question", "options", "correct_answer", "explanation"]
                }
              }
            },
            required: ["quiz_title", "language", "difficulty", "questions"]
          }
        }
      });

      if (!result || !result.text) {
        throw new Error("Empty response from Gemini");
      }

      // Safe JSON cleaning and parsing server-side
      let text = result.text.trim();
      // Remove any unintentional markdown
      if (text.startsWith("```")) {
        text = text.replace(/^```json\n?/, "").replace(/\n?```$/, "");
      }

      const quizData = JSON.parse(text);
      
      // Basic validation
      if (!quizData.questions || !Array.isArray(quizData.questions)) {
        throw new Error("Invalid question structure in AI response");
      }

      res.status(200).json(quizData);
    } catch (error) {
      console.error("Quiz Gen Error:", error);
      res.status(500).json({ error: "Failed to generate quiz instantly", details: error instanceof Error ? error.message : "AI Error" });
    }
  });

  // API Routes
  app.get("/api/rpsc", (req, res) => {
    // Simulating dynamic data with timestamps in the last few days
    const now = new Date();
    
    // Randomize some fields to simulate "real-time" changes for the user's demo
    const statuses = ["Exam Date", "Admit Card", "Result", "New Notification", "Answer Key"];
    const departments = ["Education", "Medical & Health", "Revenue", "Home Department", "Ayurved"];
    
    const notifications = [
      {
        id: "1",
        title: "Press Note regarding Exam Date for RAS/RTS Comb. Comp. Exam 2026",
        date: new Date(now.getTime() - 1000 * 60 * 45).toISOString(), // 45 mins ago
        category: "Exams",
        isNew: true,
        department: "General Administration",
        status: "Exam Date"
      },
      {
        id: "2",
        title: "Extended Date for Online Application for Lecturer (Sanskrit Edu.) - 2026",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(), // 3 hours ago
        category: "Recruitment",
        isNew: true,
        department: "Sanskrit Education",
        status: "New Notification"
      },
      {
        id: "3",
        title: "Question Paper for Statistical Officer Exam 2025 (Economics & Statistics)",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
        category: "Question Papers",
        isNew: false,
        department: "Economics & Statistics",
        status: "Answer Key"
      },
      {
        id: "4",
        title: "Final Answer Key for Assistant Professor (College Edu.) - 2024",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
        category: "Results",
        isNew: false,
        department: "College Education",
        status: "Result"
      },
      {
        id: "5",
        title: "Admit Card Download for Junior Legal Officer (JLO) 2025",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
        category: "Admit Cards",
        isNew: false,
        department: "Law Department",
        status: "Admit Card"
      }
    ];

    // Add some random noise to simulate 'live' data changing
    if (Math.random() > 0.7) {
        notifications.unshift({
            id: `temp-${Date.now()}`,
            title: `URGENT: Press note regarding ${departments[Math.floor(Math.random() * departments.length)]} Interview Schedule`,
            date: new Date().toISOString(),
            category: "Interview",
            isNew: true,
            department: departments[Math.floor(Math.random() * departments.length)],
            status: statuses[Math.floor(Math.random() * statuses.length)]
        });
    }

    res.json({
        success: true,
        lastUpdated: now.toISOString(),
        data: notifications
    });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*all", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
