import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

// Initialize Gemini
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for JSON parsing
  app.use(express.json());

  // AI Video Engine: Analysis & Scripting
  app.post("/api/video/script", async (req, res) => {
    const { content, type } = req.body;
    
    try {
      const prompt = `
        You are a Cinematic AI Video Director specializing in Educational Content for competitive exams (RPSC).
        The user has provided this content: "${content}"
        The video type requested is: "${type || 'Reel'}"
        
        Create a detailed storyboard for a 15-30 second educational video.
        Follow these "Suzume" and "Anime Cinematic" visual rules:
        - High-quality anime visuals, environment lighting like Shinkai films.
        - Protagonist: A study assistant character (Anime topper style) or a cute wild cat cub mascot.
        - Scenes should have natural forest lighting, realistic shadows, and particles.
        
        Generate exactly 4 scenes. For each scene, provide:
        1. Visual Prompt (detailed for an image generator)
        2. Narration Script (Short, impactful)
        3. On-screen text (Keywords)
        4. Camera movement (e.g., slow zoom, pan right)
        5. Music vibe
        6. Duration in seconds (sum should be around 20-30s)
      `;

      const result = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              summary: { type: Type.STRING },
              scenes: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    visualPrompt: { type: Type.STRING },
                    narration: { type: Type.STRING },
                    overlayText: { type: Type.STRING },
                    camera: { type: Type.STRING },
                    duration: { type: Type.NUMBER },
                    music: { type: Type.STRING }
                  },
                  required: ["visualPrompt", "narration", "overlayText", "camera", "duration", "music"]
                }
              },
              characterState: { type: Type.STRING, description: "mascot emotion for the video" }
            },
            required: ["title", "summary", "scenes", "characterState"]
          }
        }
      });

      res.json(JSON.parse(result.text || "{}"));
    } catch (error) {
      console.error("Video Script Error:", error);
      res.status(500).json({ error: "Failed to generate video script" });
    }
  });

  // AI Video Engine: Visual Generation
  app.post("/api/video/visual", async (req, res) => {
    const { prompt } = req.body;
    
    try {
      // Use gemini-2.5-flash-image for general AI imagery
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: `${prompt}, high quality anime cinematic style, suzume environment lighting, 4k, digital art, vibrant colors, realistic shadows` }],
        },
        config: {
          imageConfig: {
            aspectRatio: "9:16", // Default to vertical/reel format
            imageSize: "1K"
          }
        }
      });

      let imageUrl = "";
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (imageUrl) {
        res.json({ imageUrl });
      } else {
        throw new Error("No image generated by model");
      }
    } catch (error) {
      console.error("Visual Gen Error:", error);
      res.status(500).json({ error: "Failed to generate visual" });
    }
  });

  // API Routes
  app.get("/api/rpsc", (req, res) => {
    // Simulating dynamic data with timestamps in the last few days
    const now = new Date();
    
    // Randomize some fields to simulate "real-time" changes for the user's demo
    const statuses = ["Exam Date", "Admit Card", "Result", "New Notification", "Answer Key"];
    const departments = ["Education", "Medical & Health", "Revenue", "Home Department", "Ayurved"];
    
    const notifications = [
      {
        id: "1",
        title: "Press Note regarding Exam Date for RAS/RTS Comb. Comp. Exam 2026",
        date: new Date(now.getTime() - 1000 * 60 * 45).toISOString(), // 45 mins ago
        category: "Exams",
        isNew: true,
        department: "General Administration",
        status: "Exam Date"
      },
      {
        id: "2",
        title: "Extended Date for Online Application for Lecturer (Sanskrit Edu.) - 2026",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(), // 3 hours ago
        category: "Recruitment",
        isNew: true,
        department: "Sanskrit Education",
        status: "New Notification"
      },
      {
        id: "3",
        title: "Question Paper for Statistical Officer Exam 2025 (Economics & Statistics)",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
        category: "Question Papers",
        isNew: false,
        department: "Economics & Statistics",
        status: "Answer Key"
      },
      {
        id: "4",
        title: "Final Answer Key for Assistant Professor (College Edu.) - 2024",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
        category: "Results",
        isNew: false,
        department: "College Education",
        status: "Result"
      },
      {
        id: "5",
        title: "Admit Card Download for Junior Legal Officer (JLO) 2025",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
        category: "Admit Cards",
        isNew: false,
        department: "Law Department",
        status: "Admit Card"
      }
    ];

    // Add some random noise to simulate 'live' data changing
    if (Math.random() > 0.7) {
        notifications.unshift({
            id: `temp-${Date.now()}`,
            title: `URGENT: Press note regarding ${departments[Math.floor(Math.random() * departments.length)]} Interview Schedule`,
            date: new Date().toISOString(),
            category: "Interview",
            isNew: true,
            department: departments[Math.floor(Math.random() * departments.length)],
            status: statuses[Math.floor(Math.random() * statuses.length)]
        });
    }

    res.json({
        success: true,
        lastUpdated: now.toISOString(),
        data: notifications
    });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*all", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
