import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

// Initialize Gemini
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for JSON parsing
  app.use(express.json());

  // AI Video Engine: Analysis & Scripting
  app.post("/api/video/script", async (req, res) => {
    const { content, type } = req.body;
    
    try {
      const prompt = `
        You are a Cinematic AI Video Director specializing in Educational Content for competitive exams (RPSC).
        The user has provided this content: "${content}"
        The video type requested is: "${type || 'Reel'}"
        
        Create a detailed storyboard for a 15-30 second educational video.
        Follow these "Suzume" and "Anime Cinematic" visual rules:
        - High-quality anime visuals, environment lighting like Shinkai films.
        - Protagonist: A study assistant character (Anime topper style) or a cute wild cat cub mascot.
        - Scenes should have natural forest lighting, realistic shadows, and particles.
        
        Generate exactly 4 scenes. For each scene, provide:
        1. Visual Prompt (detailed for an image generator)
        2. Narration Script (Short, impactful)
        3. On-screen text (Keywords)
        4. Camera movement (e.g., slow zoom, pan right)
        5. Music vibe
        6. Duration in seconds (sum should be around 20-30s)
      `;

      const result = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              summary: { type: Type.STRING },
              scenes: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    visualPrompt: { type: Type.STRING },
                    narration: { type: Type.STRING },
                    overlayText: { type: Type.STRING },
                    camera: { type: Type.STRING },
                    duration: { type: Type.NUMBER },
                    music: { type: Type.STRING }
                  },
                  required: ["visualPrompt", "narration", "overlayText", "camera", "duration", "music"]
                }
              },
              characterState: { type: Type.STRING, description: "mascot emotion for the video" }
            },
            required: ["title", "summary", "scenes", "characterState"]
          }
        }
      });

      res.json(JSON.parse(result.text || "{}"));
    } catch (error) {
      console.error("Video Script Error:", error);
      res.status(500).json({ error: "Failed to generate video script" });
    }
  });

  // AI Video Engine: Visual Generation
  app.post("/api/video/visual", async (req, res) => {
    const { prompt } = req.body;
    
    try {
      // Use gemini-2.5-flash-image for general AI imagery
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: `${prompt}, high quality anime cinematic style, suzume environment lighting, 4k, digital art, vibrant colors, realistic shadows` }],
        },
        config: {
          imageConfig: {
            aspectRatio: "9:16", // Default to vertical/reel format
            imageSize: "1K"
          }
        }
      });

      let imageUrl = "";
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (imageUrl) {
        res.json({ imageUrl });
      } else {
        throw new Error("No image generated by model");
      }
    } catch (error) {
      console.error("Visual Gen Error:", error);
      res.status(500).json({ error: "Failed to generate visual" });
    }
  });

  // API Routes
  app.get("/api/rpsc", (req, res) => {
    // Simulating dynamic data with timestamps in the last few days
    const now = new Date();
    
    // Randomize some fields to simulate "real-time" changes for the user's demo
    const statuses = ["Exam Date", "Admit Card", "Result", "New Notification", "Answer Key"];
    const departments = ["Education", "Medical & Health", "Revenue", "Home Department", "Ayurved"];
    
    const notifications = [
      {
        id: "1",
        title: "Press Note regarding Exam Date for RAS/RTS Comb. Comp. Exam 2026",
        date: new Date(now.getTime() - 1000 * 60 * 45).toISOString(), // 45 mins ago
        category: "Exams",
        isNew: true,
        department: "General Administration",
        status: "Exam Date"
      },
      {
        id: "2",
        title: "Extended Date for Online Application for Lecturer (Sanskrit Edu.) - 2026",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(), // 3 hours ago
        category: "Recruitment",
        isNew: true,
        department: "Sanskrit Education",
        status: "New Notification"
      },
      {
        id: "3",
        title: "Question Paper for Statistical Officer Exam 2025 (Economics & Statistics)",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
        category: "Question Papers",
        isNew: false,
        department: "Economics & Statistics",
        status: "Answer Key"
      },
      {
        id: "4",
        title: "Final Answer Key for Assistant Professor (College Edu.) - 2024",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
        category: "Results",
        isNew: false,
        department: "College Education",
        status: "Result"
      },
      {
        id: "5",
        title: "Admit Card Download for Junior Legal Officer (JLO) 2025",
        date: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
        category: "Admit Cards",
        isNew: false,
        department: "Law Department",
        status: "Admit Card"
      }
    ];

    // Add some random noise to simulate 'live' data changing
    if (Math.random() > 0.7) {
        notifications.unshift({
            id: `temp-${Date.now()}`,
            title: `URGENT: Press note regarding ${departments[Math.floor(Math.random() * departments.length)]} Interview Schedule`,
            date: new Date().toISOString(),
            category: "Interview",
            isNew: true,
            department: departments[Math.floor(Math.random() * departments.length)],
            status: statuses[Math.floor(Math.random() * statuses.length)]
        });
    }

    res.json({
        success: true,
        lastUpdated: now.toISOString(),
        data: notifications
    });
  });

  // Safe parser helper function to extract and parse JSON strictly and cleanly
  const cleanAndParseJSON = (text: string): any => {
    if (!text) return [];
    let cleanText = text.trim();
    
    // Remove markdown code block markers if present
    if (cleanText.startsWith("```")) {
      cleanText = cleanText.replace(/^```(json)?/, "").replace(/```$/, "").trim();
    }
    
    // Direct parse
    try {
      return JSON.parse(cleanText);
    } catch (err) {
      console.warn("[Server Safe Parser] Direct JSON parse failed, trying extraction...", err);
    }
    
    // Try to extract content inside the first array brackets [...]
    try {
      const firstBracket = cleanText.indexOf("[");
      const lastBracket = cleanText.lastIndexOf("]");
      if (firstBracket !== -1 && lastBracket > firstBracket) {
        const candidate = cleanText.substring(firstBracket, lastBracket + 1);
        return JSON.parse(candidate);
      }
    } catch (err) {
      console.warn("[Server Safe Parser] Bracket extraction failed:", err);
    }

    // Try to extract content inside the first object braces {...}
    try {
      const firstBrace = cleanText.indexOf("{");
      const lastBrace = cleanText.lastIndexOf("}");
      if (firstBrace !== -1 && lastBrace > firstBrace) {
        const candidate = cleanText.substring(firstBrace, lastBrace + 1);
        const parsedObj = JSON.parse(candidate);
        if (Array.isArray(parsedObj)) return parsedObj;
        if (parsedObj.questions && Array.isArray(parsedObj.questions)) return parsedObj.questions;
        if (parsedObj.data && Array.isArray(parsedObj.data)) return parsedObj.data;
        return [parsedObj];
      }
    } catch (err) {
      console.error("[Server Safe Parser] Braces extraction failed:", err);
    }
    
    return [];
  };

  // API Route: Secure Server-side Quiz Questions Generator using recommended Gemini model with reliable schema
  app.post("/api/quiz/generate", async (req, res) => {
    const { config } = req.body;
    if (!config) {
      return res.status(400).json({ error: "Missing config parameters" });
    }
    const { subject, difficulty, language, questionCount, topic, pattern, mode } = config;

    const count = questionCount || 5;

    try {
      const isCurrentAffairs = subject === 'Rajasthan Current Affairs' || subject === 'National Current Affairs' || subject === 'Daily Live Quiz';
      const isLiveQuiz = subject === 'Daily Live Quiz';
      const isDailyChallenge = mode === 'daily';

      const patternScope = pattern === '2012-2020' 
        ? 'Old Pattern (2012–2020): Direct factual questions, simple recall-based, traditional government tests.' 
        : 'New Pattern (2021–2026): Complex statement-based MCQs, confusing high-degree distractors, analytical, modern CBT government exam portals style.';

      const examStyles = [
        "Standard MCQ: Direct, hard factual question with 4 complex but distinct options based on official government records.",
        "Statement-based: Give 2-3 detailed clauses/statements, and ask the candidate to determine which ones are correct (e.g., Options: A. Only 1, B. 1 and 2, C. 2 and 3, D. All are correct). Very realistic for RAS.",
        "Assertion & Reason: Specify an Assertion (A) and Reason (R), with classic options: A. Both A and R are true and R is correct explanation of A; B. Both A and R are true but R is not the correct explanation of A; C. A is true but R is false; D. A is false but R is true.",
        "Chronology: List 4-5 historical events, rulers, treaties, or government schemes, and ask the user to choose the correct chronological sequence in the options.",
        "Match the Column: Present two columns (Column I and Column II) mapping districts to features, authors to books, schemes to years, and ask the user to choose the correct mapping matrix from options."
      ];

      const selectedStyle = examStyles[Math.floor(Math.random() * examStyles.length)];
      
      let prompt = "";
      if (isDailyChallenge) {
        prompt = `
        Persona: You are an elite AI Quiz Paper Setter for challenging state exams like RPSC, REET, RAS, CET, and Rajasthan Police.
        Task: Generate exactly ${count} top-tier government-exam level MCQs for "Daily 10 Challenge".
        
        RULES:
        1. Generate EXACTLY ${count} questions. No more, no less.
        2. High quality only: Incorporate authentic current affairs (2025-2026) and difficult core syllabus.
        3. Subject mix: General Knowledge, Rajasthan history, geography, culture, polity, math/reasoning, and science.
        4. Language: '${language}'.
           - If Bilingual: Each question and answer MUST be bilingual (Hindi and English fields populated).
           - If Hindi: Generate Hindi content.
           - If English: Generate English content.
        `;
      } else if (isLiveQuiz) {
        prompt = `
        Persona: You are an expert RPSC & UPSC Current Affairs researcher.
        Task: Search current affairs and official government resources to generate ${count} GK questions.
        
        INSTRUCTIONS:
        1. SEARCH: Find real, actual happenings from the last 24-48 hours.
        2. EXAM TYPES: Match REET, CET, RPSC, UPSC, and Rajasthan Police high-standard examinations.
        3. BILINGUAL SUPPORT: Support '${language}' format completely.
        `;
      } else {
        prompt = `
        Persona: You are a senior RPSC, REET, CET, or Rajasthan Police board paper setter. 
        Generate ${count} extremely realistic, highly competitive exam questions.
        Subject Area: ${subject}
        ${topic ? `Focus Topic: ${topic}` : ''}
        Level: ${difficulty}
        Language: ${language}
        Exam Standard: ${patternScope}
        Question Layout Pattern: ${selectedStyle}

        EXAM SETTER COMPLIANCE:
        1. STYLE: Question MUST resemble official government exam portal questions.
        2. DISTRACTORS: Options (A, B, C, D) must have professional distractors (no silly or obvious answers).
        3. REPETITION: No duplicated questions. Vary the concepts tested.
        4. SPECIFICS: Focus heavily on Rajasthan and National administration, history, modern current affairs, maps/geography, and statement-based structures.
        `;
      }

      console.log(`[Server AI] Generating ${count} MCQs, subject: ${subject}, language: ${language}`);
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt + `\n\nReturn EXACTLY ${count} items. Strictly follow the JSON schema array structure containing ${count} questions.`,
        config: {
          responseMimeType: "application/json",
          maxOutputTokens: 8192, // Increase output token limit to prevent truncation
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                question: { type: Type.STRING },
                question_hindi: { type: Type.STRING },
                question_english: { type: Type.STRING },
                options: {
                  type: Type.OBJECT,
                  properties: {
                    A: { type: Type.STRING },
                    B: { type: Type.STRING },
                    C: { type: Type.STRING },
                    D: { type: Type.STRING }
                  },
                  required: ["A", "B", "C", "D"]
                },
                options_bilingual: {
                  type: Type.OBJECT,
                  properties: {
                    A: {
                      type: Type.OBJECT,
                      properties: { hindi: { type: Type.STRING }, english: { type: Type.STRING } },
                      required: ["hindi", "english"]
                    },
                    B: {
                      type: Type.OBJECT,
                      properties: { hindi: { type: Type.STRING }, english: { type: Type.STRING } },
                      required: ["hindi", "english"]
                    },
                    C: {
                      type: Type.OBJECT,
                      properties: { hindi: { type: Type.STRING }, english: { type: Type.STRING } },
                      required: ["hindi", "english"]
                    },
                    D: {
                      type: Type.OBJECT,
                      properties: { hindi: { type: Type.STRING }, english: { type: Type.STRING } },
                      required: ["hindi", "english"]
                    }
                  }
                },
                correctAnswer: { type: Type.STRING, enum: ["A", "B", "C", "D"] },
                explanation: { type: Type.STRING },
                explanation_hindi: { type: Type.STRING },
                explanation_english: { type: Type.STRING },
                difficulty: { type: Type.STRING },
                wrongOptionsAnalysis: {
                  type: Type.OBJECT,
                  properties: {
                    A: { type: Type.STRING },
                    B: { type: Type.STRING },
                    C: { type: Type.STRING },
                    D: { type: Type.STRING }
                  }
                },
                teacherInsight: { type: Type.STRING },
                extraFacts: { type: Type.ARRAY, items: { type: Type.STRING } }
              },
              required: ["question", "options", "correctAnswer", "explanation"]
            }
          }
        }
      });

      const responseText = response.text || "[]";
      let rawQuestions = [];
      try {
        rawQuestions = cleanAndParseJSON(responseText);
      } catch (parseErr) {
        console.error("[Server AI] JSON Parsing of response failed:", parseErr, responseText);
        throw new Error("Invalid or broken JSON from model output");
      }

      if (!Array.isArray(rawQuestions) || rawQuestions.length === 0) {
        console.warn("[Server AI] Parsed questions array is empty. Returning empty questions array for client fallback.");
        return res.json({ success: true, questions: [] });
      }

      const normalizedAnswers = rawQuestions.map((q: any, idx: number) => {
        let options = q.options;
        if (language === 'Bilingual' && q.options_bilingual) {
          const ob = q.options_bilingual;
          options = {
            A: ob.A ? `${ob.A.hindi || ''} / ${ob.A.english || ''}` : options.A,
            B: ob.B ? `${ob.B.hindi || ''} / ${ob.B.english || ''}` : options.B,
            C: ob.C ? `${ob.C.hindi || ''} / ${ob.C.english || ''}` : options.C,
            D: ob.D ? `${ob.D.hindi || ''} / ${ob.D.english || ''}` : options.D,
          };
        }

        let questionText = q.question;
        let explanationText = q.explanation || q.explanation_hindi || q.explanation_english;

        if (language === 'Bilingual') {
          questionText = `${q.question_hindi || q.question}\n\n${q.question_english || q.question}`;
          explanationText = `${q.explanation_hindi || explanationText || ''}\n\n${q.explanation_english || explanationText || ''}`;
        } else if (language === 'Hindi') {
          questionText = q.question_hindi || q.question;
          explanationText = q.explanation_hindi || explanationText;
        } else if (language === 'English') {
          questionText = q.question_english || q.question;
          explanationText = q.explanation_english || explanationText;
        }

        return {
          id: `gen-${subject}-${idx}-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
          question: questionText,
          options: options,
          correctAnswer: q.correctAnswer || "A",
          explanation: explanationText || "Expert explanation for this concept.",
          explanationHindi: q.explanation_hindi || q.explanation || "",
          explanationEnglish: q.explanation_english || q.explanation || "",
          teacherInsight: q.teacherInsight || "Study regular revisions of state topics for better memory.",
          wrongOptionsAnalysis: q.wrongOptionsAnalysis || { A: "Incorrect option", B: "Incorrect option", C: "Incorrect option", D: "Incorrect option" },
          extraFacts: q.extraFacts || [],
          subject: subject,
          question_hindi: q.question_hindi || "",
          question_english: q.question_english || "",
          options_bilingual: q.options_bilingual || null
        };
      });

      res.json({ success: true, questions: normalizedAnswers });
    } catch (err) {
      console.error("[Server AI] Quiz generation error:", err);
      res.status(500).json({ error: "Failed to generate questions server-side" });
    }
  });

  // API Route: Secure Server-side Search Grounded RPSC Notifications fetcher
  app.get("/api/rpsc/notifications", async (req, res) => {
    try {
      const prompt = `
        Persona: You are a reliable academic assistant.
        Task: Use Google Search to find the 5 most recent and relevant notifications from the RPSC (Rajasthan Public Service Commission) official website or trusted news sources.
        Requirements: Include upcoming exam dates for RAS, First Grade, Second Grade, and other major exams planned for 2024-2026.
      `;

      console.log(`[Server AI] Fetching live grounded notifications...`);
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          tools: [{ googleSearch: {} }],
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                title: { type: Type.STRING },
                date: { type: Type.STRING },
                link: { type: Type.STRING },
                type: { type: Type.STRING, enum: ["EXAM", "RESULT", "NEWS"] },
                description: { type: Type.STRING }
              },
              required: ["title", "date", "type", "description"]
            }
          }
        }
      });

      const notifications = JSON.parse(response.text || "[]");
      res.json({ success: true, notifications });
    } catch (err) {
      console.error("[Server AI] Notification retrieval error:", err);
      // Return simulated static notices as a bulletproof runtime backup
      res.json({
        success: true,
        notifications: [
          {
            title: "Press Note regarding Exam Date for RAS/RTS Comb. Comp. Exam 2026",
            date: "May 20, 2026",
            link: "https://rpsc.rajasthan.gov.in",
            type: "EXAM",
            description: "The RAS examination phase schedule has been officially updated on the commission board notice."
          },
          {
            title: "Extended Date for Online Application for Lecturer (Sanskrit Edu.) - 2026",
            date: "May 19, 2026",
            link: "https://rpsc.rajasthan.gov.in",
            type: "NEWS",
            description: "Extended deadline notice for lectureship applications across certified state colleges."
          }
        ]
      });
    }
  });

  // API Route: Secure Server-side Video Learning Analyst
  app.post("/api/video/analyze", async (req, res) => {
    const { video } = req.body;
    if (!video) {
      return res.status(400).json({ error: "Missing video parameter" });
    }

    try {
      const prompt = `
        Persona: You are a Video Learning Analyst for RPSC exams. 
        Video Title: ${video.title}
        Channel: ${video.channelTitle}
        Description: ${video.description}

        TASK:
        1. Summarize the core educational concepts of this video.
        2. Identify 3-5 key topics covered.
        3. Generate a 3-question mini quiz (MCQ) to test the user after watching.
        4. Propose 2 "Review Segments" with estimated timestamps (e.g., 05:30) and WHY the student should focus on that part.
      `;

      console.log(`[Server AI] Analyzing educational video: ${video.title}`);
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              summary: { type: Type.STRING },
              keyTopics: { type: Type.ARRAY, items: { type: Type.STRING } },
              miniQuiz: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    question: { type: Type.STRING },
                    options: { type: Type.ARRAY, items: { type: Type.STRING } },
                    correctIndex: { type: Type.NUMBER },
                    explanation: { type: Type.STRING }
                  },
                  required: ["question", "options", "correctIndex", "explanation"]
                }
              },
              reviewSegments: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    title: { type: Type.STRING },
                    timestamp: { type: Type.STRING },
                    seconds: { type: Type.NUMBER },
                    reason: { type: Type.STRING }
                  },
                  required: ["title", "timestamp", "seconds", "reason"]
                }
              }
            },
            required: ["summary", "keyTopics", "miniQuiz", "reviewSegments"]
          }
        }
      });

      const analysis = JSON.parse(response.text || "{}");
      res.json({ success: true, analysis });
    } catch (err) {
      console.error("[Server AI] Video analysis error:", err);
      res.status(500).json({ error: "Failed to analyze video" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*all", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
